name: ci-frontend

on:
  pull_request:
    branches: ["main", "develop"]
    paths:
      - "frontend/**"
jobs:
  check-frontend:
    name: check-frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: create env files
        run: |
          touch .env.production
          cat << EOF > .env.production
          ${{ secrets.FE_ENV_PRODUCTION }}
          EOF
          touch .env.test
          cat << EOF > .env.test
          ${{ secrets.FE_ENV_TEST }}
          EOF

      - name: install dependencies
        run: npm i

      - name: lint test
        run: npm run lint

      - name: unit test
        run: npm run test

      - name: build
        run: npm run build
